.TH "ChannelData" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelData \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBChan1\fP"
.br
.ti -1c
.RI "int \fBChan2\fP"
.br
.ti -1c
.RI "int \fBChan3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file TIM1\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int Chan1"

.PP
Definition at line 16 of file TIM1\&.c\&.
.SS "int Chan2"

.PP
Definition at line 17 of file TIM1\&.c\&.
.SS "int Chan3"

.PP
Definition at line 18 of file TIM1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
