.TH "charReceiverList_t" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charReceiverList_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <charReceiverList\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBmax_size\fP"
.br
.RI "\fImax_size \fP"
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "\fIsize \fP"
.ti -1c
.RI "\fBcharReceiver_t\fP * \fBreceivers\fP"
.br
.RI "\fIreceivers \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
Atharva A\&. Document this structure (when done change this line to '@todo MM check <your names> documentation' 
.RE
.PP

.PP
Definition at line 33 of file charReceiverList\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t max_size"

.PP
max_size 
.PP
Definition at line 34 of file charReceiverList\&.h\&.
.SS "\fBcharReceiver_t\fP* receivers"

.PP
receivers 
.PP
Definition at line 36 of file charReceiverList\&.h\&.
.SS "uint16_t size"

.PP
size 
.PP
Definition at line 35 of file charReceiverList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
