.TH "hal_settings.h" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_settings.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFCPU\fP   1048576L"
.br
.ti -1c
.RI "#define \fBPERIPHERAL_CLOCK\fP   \fBFCPU\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FCPU   1048576L"

.PP
Definition at line 4 of file hal_settings\&.h\&.
.SS "#define PERIPHERAL_CLOCK   \fBFCPU\fP"

.PP
Definition at line 5 of file hal_settings\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
