.TH "hal_timing.c" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_timing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <msp430\&.h>\fP
.br
\fC#include 'timing\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhal_Timing_Init\fP (void)"
.br
.ti -1c
.RI "__interrupt void \fBTIMER0_A0_ISR\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__interrupt void TIMER0_A0_ISR (void)"

.PP
Definition at line 17 of file hal_timing\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
