.TH "hal_timing.h" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal_timing.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhal_Timing_Init\fP (void)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
