.TH "list_link_t" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_link_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBitem_ptr\fP"
.br
.RI "\fIitem_ptr \fP"
.ti -1c
.RI "struct \fBlist_link_t\fP * \fBnext\fP"
.br
.RI "\fInext \fP"
.ti -1c
.RI "struct \fBlist_link_t\fP * \fBprevious\fP"
.br
.RI "\fIprevious \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
Matthew D\&. Document this struct (when done change this line to '@todo MM check <your names> documentation' 
.RE
.PP

.PP
Definition at line 27 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* item_ptr"

.PP
item_ptr 
.PP
Definition at line 28 of file list\&.h\&.
.SS "struct \fBlist_link_t\fP* next"

.PP
next 
.PP
Definition at line 29 of file list\&.h\&.
.SS "struct \fBlist_link_t\fP* previous"

.PP
previous 
.PP
Definition at line 30 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
