.TH "list_t" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
list_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlist_link_t\fP * \fBfirst\fP"
.br
.RI "\fIfirst \fP"
.ti -1c
.RI "\fBlist_link_t\fP * \fBlast\fP"
.br
.RI "\fIlast \fP"
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.RI "\fIlength \fP"
.ti -1c
.RI "uint16_t \fBarray_length\fP"
.br
.RI "\fIarray_length \fP"
.ti -1c
.RI "\fBlist_link_t\fP * \fBlinks\fP"
.br
.RI "\fIlinks \fP"
.ti -1c
.RI "uint16_t * \fBitem_array\fP"
.br
.RI "\fIitem_array \fP"
.ti -1c
.RI "uint16_t \fBitem_size\fP"
.br
.RI "\fIitem_size \fP"
.ti -1c
.RI "\fBsort_fn_t\fP \fBsort_fn\fP"
.br
.RI "\fIsort_fn \fP"
.ti -1c
.RI "\fBidentify_fn_t\fP \fBidentify_fn\fP"
.br
.RI "\fIidentify_fn \fP"
.ti -1c
.RI "\fBlist_link_t\fP * \fBworking\fP [2]"
.br
.RI "\fIworking \fP"
.ti -1c
.RI "\fBlist_link_t\fP * \fBunlinked\fP [2]"
.br
.RI "\fIunlinked \fP"
.ti -1c
.RI "\fBlist_link_t\fP * \fBunused\fP [2]"
.br
.RI "\fIunused \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
Jacob H\&. Document this struct (when done change this line to '@todo MM check <your names> documentation' 
.RE
.PP

.PP
Definition at line 36 of file list\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t array_length"

.PP
array_length 
.PP
Definition at line 40 of file list\&.h\&.
.SS "\fBlist_link_t\fP* first"

.PP
first 
.PP
Definition at line 37 of file list\&.h\&.
.SS "\fBidentify_fn_t\fP identify_fn"

.PP
identify_fn 
.PP
Definition at line 45 of file list\&.h\&.
.SS "uint16_t* item_array"

.PP
item_array 
.PP
Definition at line 42 of file list\&.h\&.
.SS "uint16_t item_size"

.PP
item_size 
.PP
Definition at line 43 of file list\&.h\&.
.SS "\fBlist_link_t\fP* last"

.PP
last 
.PP
Definition at line 38 of file list\&.h\&.
.SS "uint16_t length"

.PP
length 
.PP
Definition at line 39 of file list\&.h\&.
.SS "\fBlist_link_t\fP* links"

.PP
links 
.PP
Definition at line 41 of file list\&.h\&.
.SS "\fBsort_fn_t\fP sort_fn"

.PP
sort_fn 
.PP
Definition at line 44 of file list\&.h\&.
.SS "\fBlist_link_t\fP* unlinked[2]"

.PP
unlinked 
.PP
Definition at line 49 of file list\&.h\&.
.SS "\fBlist_link_t\fP* unused[2]"

.PP
unused 
.PP
Definition at line 50 of file list\&.h\&.
.SS "\fBlist_link_t\fP* working[2]"

.PP
working 
.PP
Definition at line 48 of file list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
