.TH "main.c" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <msp430\&.h>\fP
.br
\fC#include 'library\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_CHANNEL\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_CHANNEL   1"

.PP
Definition at line 6 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int32_t main (void)"

.PP
Definition at line 8 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
