.TH "META_TEDS" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
META_TEDS \- Contains all basic Information for the TIM; calls upon the \fBMetaTEDSInit()\fP function in \fBTIM1\&.h\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TIM_Core\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBMetaTEDSLength\fP"
.br
.ti -1c
.RI "uint8_t \fBIEEE1451WGNum\fP"
.br
.ti -1c
.RI "uint8_t \fBTEDSVersionNum\fP"
.br
.ti -1c
.RI "uint8_t \fBCH0IndCalExtKey\fP"
.br
.ti -1c
.RI "uint8_t \fBCH0IndDataExtKey\fP"
.br
.ti -1c
.RI "uint8_t \fBCH0TEDSExtKey\fP"
.br
.ti -1c
.RI "uint8_t \fBCH0EUAppKey\fP"
.br
.ti -1c
.RI "uint8_t \fBWCChanDataLen\fP"
.br
.ti -1c
.RI "uint16_t \fBWCChanDataRep\fP"
.br
.ti -1c
.RI "uint32_t \fBCH0WrTEDSLen\fP"
.br
.ti -1c
.RI "float \fBTWU\fP"
.br
.ti -1c
.RI "float \fBTGWS\fP"
.br
.ti -1c
.RI "float \fBTGRS\fP"
.br
.ti -1c
.RI "float \fBTWSP\fP"
.br
.ti -1c
.RI "float \fBTWWUT\fP"
.br
.ti -1c
.RI "float \fBCRT\fP"
.br
.ti -1c
.RI "float \fBTHS\fP"
.br
.ti -1c
.RI "float \fBTLAT\fP"
.br
.ti -1c
.RI "float \fBTTH\fP"
.br
.ti -1c
.RI "float \fBTOH\fP"
.br
.ti -1c
.RI "uint32_t \fBMDR\fP"
.br
.ti -1c
.RI "uint16_t \fBChanGroupLen\fP"
.br
.ti -1c
.RI "uint8_t \fBNumChanGroup\fP"
.br
.ti -1c
.RI "uint16_t \fBMTChecksum\fP"
.br
.ti -1c
.RI "char \fBGloballyUID\fP [10]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all basic Information for the TIM; calls upon the \fBMetaTEDSInit()\fP function in \fBTIM1\&.h\fP\&. 

All TIMs on a network need a TEDS to tell the NCAP what exactly it is capable of\&. The first type of TEDS the NCAP will attempt to read is the MetaTEDS which contains information about how many sensor channels there are, worst case sampling times, as well as other communication and initialization information\&. The fields and their applicable data types can be found in the IEEE P21451-2 documentation\&. 
.PP
Definition at line 57 of file TIM_Core\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t CH0EUAppKey"
This field indicates the presence of End-Users’ Application-Specific TEDS function in CHANNEL_ZERO\&. 
.PP
Definition at line 64 of file TIM_Core\&.h\&.
.SS "uint8_t CH0IndCalExtKey"
The value in this field indicates the highest functional address for writing the industry-implemented Calibration TEDS extension that is available in the STIM for CHANNEL_ZERO\&. 
.PP
Definition at line 61 of file TIM_Core\&.h\&.
.SS "uint8_t CH0IndDataExtKey"
The value in this field indicates the highest functional address for writing the industry-implemented nonvolatile data field extensions that is available in the STIM for CHANNEL_ZERO\&. 
.PP
Definition at line 62 of file TIM_Core\&.h\&.
.SS "uint8_t CH0TEDSExtKey"
The value in this field indicates the highest functional address for writing the industry-implemented TEDS extensions that is available in the STIM for CHANNEL_ZERO\&. 
.PP
Definition at line 63 of file TIM_Core\&.h\&.
.SS "uint32_t CH0WrTEDSLen"
This field specifies the length in bytes available for each CHANNEL_ZERO user-writable TEDS\&. 
.PP
Definition at line 67 of file TIM_Core\&.h\&.
.SS "uint16_t ChanGroupLen"
This field specifies the total number of bytes in the Channel Grouping data sub-block\&. 
.PP
Definition at line 84 of file TIM_Core\&.h\&.
.SS "float CRT"
This field specifies the longest time, in seconds, that the STIM takes to process any command\&. 
.PP
Definition at line 73 of file TIM_Core\&.h\&.
.SS "char GloballyUID[10]"
Globally Unique Identifier, as generated by an algorithm laid out in the Standard\&. 
.PP
Definition at line 87 of file TIM_Core\&.h\&.
.SS "uint8_t IEEE1451WGNum"
Working Group Number for which the following TEDs Template is laid out 
.PP
Definition at line 59 of file TIM_Core\&.h\&.
.SS "uint32_t MDR"
This field specifies the maximum data rate, in bits per second, supported by the STIM interface\&. 
.PP
Definition at line 83 of file TIM_Core\&.h\&.
.SS "uint32_t MetaTEDSLength"
Total length in Bytes of the MetaTEDS excluding this field 
.PP
Definition at line 58 of file TIM_Core\&.h\&.
.SS "uint16_t MTChecksum"
This field contains the checksum for the complete Meta-TEDS data block\&. 
.PP
Definition at line 86 of file TIM_Core\&.h\&.
.SS "uint8_t NumChanGroup"
This field specifies the number of discrete channel groupings defined in this STIM’s Meta-TEDS\&. 
.PP
Definition at line 85 of file TIM_Core\&.h\&.
.SS "uint8_t TEDSVersionNum"
Specifies the version number of the TEDS that corresponds to the particular part of the standard which the TEDS are from 
.PP
Definition at line 60 of file TIM_Core\&.h\&.
.SS "float TGRS"
This field specifies the minimum time (tgrs), in seconds, between the receipt of a global trigger acknowledge and the beginning of a global read frame\&. 
.PP
Definition at line 70 of file TIM_Core\&.h\&.
.SS "float TGWS"
This field specifies the minimum time (tgws), in seconds, between the end of a global write frame and the application of a global trigger\&. 
.PP
Definition at line 69 of file TIM_Core\&.h\&.
.SS "float THS"
This field specifies the longest time (ths), in seconds, for the STIM to remove the trigger acknowledge signal after the trigger signal is removed by the NCAP, or for the STIM to remove the data transport acknowledge signal after the data transport is inactivated by the NCAP\&. 
.PP
Definition at line 74 of file TIM_Core\&.h\&.
.SS "float TLAT"
This field specifies the longest time (tlat), in seconds, that a STIM shall take to detect the removal of the data transport enable signal\&. 
.PP
Definition at line 77 of file TIM_Core\&.h\&.
.SS "float TOH"
This field specifies the maximum individual hold-off time, in seconds, imposed by the STIM before the first byte, or between bytes, of any data transfer addressed to operational functions\&. 
.PP
Definition at line 81 of file TIM_Core\&.h\&.
.SS "float TTH"
This field specifies the maximum individual hold-off time, in seconds, imposed by the STIM before the first byte, or between bytes, of any data transfer addressed to TEDS functions\&. 
.PP
Definition at line 79 of file TIM_Core\&.h\&.
.SS "float TWSP"
This field specifies the maximum value (twsp), in seconds, of the channel sampling period for all implemented channels\&. 
.PP
Definition at line 71 of file TIM_Core\&.h\&.
.SS "float TWU"
This field specifies the maximum value of the Channel Update Time (twu) for all the implemented channels in seconds\&. 
.PP
Definition at line 68 of file TIM_Core\&.h\&.
.SS "float TWWUT"
This field specifies the minimum time, in seconds, that is necessary between application of power to the STIM and instigation of the first transducer data transfer\&. 
.PP
Definition at line 72 of file TIM_Core\&.h\&.
.SS "uint8_t WCChanDataLen"
This field specifies the maximum value of the Channel Data Model Length for all the implemented channels\&. 
.PP
Definition at line 65 of file TIM_Core\&.h\&.
.SS "uint16_t WCChanDataRep"
This field specifies the maximum value of the Channel Data Repetitions for all the implemented channels\&. 
.PP
Definition at line 66 of file TIM_Core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
