.TH "system.h" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
system.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'library\&.h'\fP
.br
\fC#include 'task\&.h'\fP
.br
\fC#include 'timing\&.h'\fP
.br
\fC#include 'list\&.h'\fP
.br
\fC#include 'buffer\&.h'\fP
.br
\fC#include 'buffer_printf\&.h'\fP
.br
\fC#include 'charReceiverList\&.h'\fP
.br
\fC#include 'itemBuffer\&.h'\fP
.br
\fC#include 'uart\&.h'\fP
.br
\fC#include 'subsys\&.h'\fP
.br
\fC#include 'hal_settings\&.h'\fP
.br
\fC#include 'random_int\&.h'\fP
.br
\fC#include 'TIM_Core\&.h'\fP
.br
\fC#include 'TIM1\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_UART1\fP"
.br
.ti -1c
.RI "#define \fBSUBSYS_UART\fP   1"
.br
.ti -1c
.RI "#define \fBUART_CHANNEL\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SUBSYS_UART   1"

.PP
Definition at line 31 of file system\&.h\&.
.SS "#define UART_CHANNEL   1"

.PP
Definition at line 32 of file system\&.h\&.
.SS "#define USE_UART1"

.PP
Definition at line 30 of file system\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
