.TH "task.h" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'timing\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTASK_ROLL_TIME\fP   (\fBTIME_MAX\fP\-(uint32_t)10*24*60*60*1000)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBtask_fn_pointer_input_t\fP) (void *)"
.br
.ti -1c
.RI "typedef void(* \fBtask_fn_t\fP) (void)"
.br
.RI "\fIdefault task type \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTask_Init\fP (void)"
.br
.ti -1c
.RI "void \fBSystemTick\fP (void)"
.br
.ti -1c
.RI "void \fBTask_Queue\fP (\fBtask_fn_t\fP fn, void *pointer)"
.br
.RI "\fIAdds a function to the task queue\&. \fP"
.ti -1c
.RI "void \fBTask_Schedule\fP (\fBtask_fn_t\fP fn, void *pointer, \fBtint_t\fP delay, \fBtint_t\fP period)"
.br
.RI "\fIAdds task to be scheduled for execution\&. \fP"
.ti -1c
.RI "void \fBTask_Remove\fP (\fBtask_fn_t\fP fn, void *pointer)"
.br
.RI "\fIRemoves Task\&. \fP"
.ti -1c
.RI "void \fBWaitMs\fP (\fBtint_t\fP wait)"
.br
.ti -1c
.RI "uint8_t \fBTask_IsScheduled\fP (\fBtask_fn_t\fP fn)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
