.TH "task_t" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_t \- task structure  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtask_fn_t\fP \fBfn\fP"
.br
.ti -1c
.RI "void * \fBpointer\fP"
.br
.ti -1c
.RI "\fBtint_t\fP \fBtime\fP"
.br
.ti -1c
.RI "\fBtint_t\fP \fBperiod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
task structure 
.PP
Definition at line 17 of file task\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBtask_fn_t\fP fn"
function to run 
.PP
Definition at line 18 of file task\&.c\&.
.SS "\fBtint_t\fP period"
the period for repeating the task if it is to be repeated 
.PP
Definition at line 21 of file task\&.c\&.
.SS "void* pointer"
pointer to pass to the task function if it is set 
.PP
Definition at line 19 of file task\&.c\&.
.SS "\fBtint_t\fP time"
the time the task was added to the queue or the time the task last ran 
.PP
Definition at line 20 of file task\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
