.TH "timing.c" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'system\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'hal_timing\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTimingISR\fP()   \fBtime\fP++"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhal_timing_Init\fP (void)"
.br
.ti -1c
.RI "void \fBTiming_Init\fP (void)"
.br
.RI "\fIInitialize the timing module\&. \fP"
.ti -1c
.RI "uint32_t \fBTimeNow\fP (void)"
.br
.RI "\fIReturns the current system time in milliseconds\&. \fP"
.ti -1c
.RI "uint32_t \fBTimeSince\fP (\fBtint_t\fP t)"
.br
.RI "\fIGet the elapsed time\&. \fP"
.ti -1c
.RI "void \fBDelayMs\fP (\fBtint_t\fP delay)"
.br
.RI "\fIDelay a specific number of milliseconds\&. \fP"
.ti -1c
.RI "void \fBTiming_Roll\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBtint_t\fP \fBtime\fP"
.br
.ti -1c
.RI "volatile \fBtint_t\fP \fBrollover_time\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TimingISR()   \fBtime\fP++"

.PP
Definition at line 14 of file timing\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void hal_timing_Init (void)"

.SH "Variable Documentation"
.PP 
.SS "volatile \fBtint_t\fP rollover_time"

.PP
Definition at line 7 of file timing\&.c\&.
.SS "volatile \fBtint_t\fP time"

.PP
Definition at line 7 of file timing\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
