.TH "todo" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBglobalScope> Global \fBcharReceiver_t\fP )(char)\fP" 1c
Alex A\&. Document this datatype (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBCharReceiverList_Add\fP (\fBcharReceiverList_t\fP *rList, charReceiver_t receiver)\fP" 1c
Kate C\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBCharReceiverList_Init\fP (\fBcharReceiverList_t\fP *rList, charReceiver_t *receiver_array, uint16_t max_size)\fP" 1c
Dan B\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBCharReceiverList_Remove\fP (\fBcharReceiverList_t\fP *rList, charReceiver_t receiver)\fP" 1c
Matthew D\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBCharReceiverList_Run\fP (\fBcharReceiverList_t\fP *rList, char c)\fP" 1c
Victor C\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBcharReceiverList_t\fP \fP" 1c
Atharva A\&. Document this structure (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBFile \fBhal_uart\&.h\fP \fP" 1c
Anthony Merlino document this
.PP
.IP "\fBglobalScope> Global \fBidentify_fn_t\fP )(void *, void *)\fP" 1c
Josh Hass Document this typedef (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBModule \fBlist\fP \fP" 1c
fill in the main comment block
.PP
.IP "\fBglobalScope> Global \fBList_Add\fP (\fBlist_t\fP *list, void *item)\fP" 1c
Joseph L\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_AddAndLink\fP (\fBlist_t\fP *list, void *item)\fP" 1c
Josh K\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_GetFirst\fP (\fBlist_t\fP *list)\fP" 1c
Josh W\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_GetItem\fP (\fBlist_t\fP *list, void *identifier)\fP" 1c
George L\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_GetLast\fP (\fBlist_t\fP *list)\fP" 1c
TJ G\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_GetNext\fP (\fBlist_t\fP *list, void *item)\fP" 1c
TJ G\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_Init\fP (\fBlist_t\fP *list, uint16_t item_size, void *item_array, uint16_t item_array_length, \fBlist_link_t\fP *link_array)\fP" 1c
Austin H\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_Link\fP (\fBlist_t\fP *list)\fP" 1c
James R\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBlist_link_t\fP \fP" 1c
Matthew D\&. Document this struct (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_LinkItem\fP (\fBlist_t\fP *list, void *item)\fP" 1c
Jon W\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_Remove\fP (\fBlist_t\fP *list, void *item)\fP" 1c
Matthew M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_RemoveAll\fP (\fBlist_t\fP *list)\fP" 1c
Anthony M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_RemoveFirst\fP (\fBlist_t\fP *list)\fP" 1c
George L\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_RemoveLast\fP (\fBlist_t\fP *list)\fP" 1c
Matthew M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_ResortFirst\fP (\fBlist_t\fP *list)\fP" 1c
Andrew R\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_ResortLast\fP (\fBlist_t\fP *list)\fP" 1c
Chris R\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_SetIdentifyFunction\fP (\fBlist_t\fP *list, uint8_t(*identify_fn)(void *identifier, void *item))\fP" 1c
Eric J\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_SetSortFunction\fP (\fBlist_t\fP *list, uint8_t(*sort_fn)(void *a, void *b))\fP" 1c
Lee H\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBlist_t\fP \fP" 1c
Jacob H\&. Document this struct (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_UnlinkFirst\fP (\fBlist_t\fP *list)\fP" 1c
Tom M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_UnlinkItem\fP (\fBlist_t\fP *list, void *item)\fP" 1c
Anthony M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBList_UnlinkLast\fP (\fBlist_t\fP *list)\fP" 1c
Tom M\&. Document this function (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBglobalScope> Global \fBMetaTEDSInit\fP (void)\fP" 1c
Implement Flash Memory read/write so that changes are saved between power cycles\&.  
.IP "\fBglobalScope> Global \fBReadChannelTransducerData\fP (char *ChannelID)\fP" 1c
Implement a proper sensor and produce readings for it\&. 
.IP "\fBglobalScope> Global \fBReadMetaTEDS\fP (void)\fP" 1c
Find a more efficient way of returning the MetaTEDS back to the NCAP\&.  
.IP "\fBglobalScope> Global \fBsort_fn_t\fP )(void *, void *)\fP" 1c
Victor C\&. Document this typedef (when done change this line to '@todo MM check <your names> documentation'  
.IP "\fBPage \fBSubSystem module command interface\fP \fP" 1c
MM Update this comment block 
.PP
MM Update this comment block  
.IP "\fBglobalScope> Global \fBTIM_Init\fP (void)\fP" 1c
Implement and call the ChannelTEDS Init funciton\&. 
.PP
Add in support for other connection mediums (NRF, SPI, etc)\&.  
.IP "\fBglobalScope> Global \fBWriteChannelTransducerData\fP (char *ChannelID, int WriteData)\fP" 1c
Find in the standard how WriteData needs to be formatted (if at all)\&. 
.PP

