.TH "uart" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uart \- UART Module
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBHAL UART Module\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
