.TH "version_t" 3 "Tue Jan 26 2016" "Version 0.1" "P21451_TIM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version_t \- version union  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subsys\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBword\fP"
.br
.ti -1c
.RI "\fBversion_mmb_t\fP \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
version union 
.PP
Definition at line 43 of file subsys\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBversion_mmb_t\fP v"
major\&.minor\&.build struct 
.PP
Definition at line 45 of file subsys\&.h\&.
.SS "uint32_t word"
32 bit version 
.PP
Definition at line 44 of file subsys\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P21451_TIM from the source code\&.
