var files =
[
    [ "buffer.c", "buffer_8c.html", "buffer_8c" ],
    [ "buffer.h", "buffer_8h.html", "buffer_8h" ],
    [ "buffer_printf.c", "buffer__printf_8c.html", "buffer__printf_8c" ],
    [ "buffer_printf.h", "buffer__printf_8h.html", "buffer__printf_8h" ],
    [ "charReceiverList.c", "char_receiver_list_8c.html", "char_receiver_list_8c" ],
    [ "charReceiverList.h", "char_receiver_list_8h.html", "char_receiver_list_8h" ],
    [ "hal_general.h", "hal__general_8h.html", "hal__general_8h" ],
    [ "hal_settings.h", "hal__settings_8h.html", "hal__settings_8h" ],
    [ "hal_timing.c", "hal__timing_8c.html", "hal__timing_8c" ],
    [ "hal_timing.h", "hal__timing_8h.html", "hal__timing_8h" ],
    [ "hal_uart.c", "hal__uart_8c.html", "hal__uart_8c" ],
    [ "hal_uart.h", "hal__uart_8h.html", "hal__uart_8h" ],
    [ "itemBuffer.c", "item_buffer_8c.html", "item_buffer_8c" ],
    [ "itemBuffer.h", "item_buffer_8h.html", "item_buffer_8h" ],
    [ "library.h", "library_8h.html", null ],
    [ "list.c", "list_8c.html", "list_8c" ],
    [ "list.h", "list_8h.html", "list_8h" ],
    [ "macros.h", "macros_8h.html", "macros_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "random_int.c", "random__int_8c.html", "random__int_8c" ],
    [ "random_int.h", "random__int_8h.html", "random__int_8h" ],
    [ "subsys.c", "subsys_8c.html", "subsys_8c" ],
    [ "subsys.h", "subsys_8h.html", "subsys_8h" ],
    [ "system.h", "system_8h.html", "system_8h" ],
    [ "task.c", "task_8c.html", "task_8c" ],
    [ "task.h", "task_8h.html", "task_8h" ],
    [ "TIM1.c", "_t_i_m1_8c.html", "_t_i_m1_8c" ],
    [ "TIM1.h", "_t_i_m1_8h.html", "_t_i_m1_8h" ],
    [ "TIM_Core.c", "_t_i_m___core_8c.html", "_t_i_m___core_8c" ],
    [ "TIM_Core.h", "_t_i_m___core_8h.html", "_t_i_m___core_8h" ],
    [ "timing.c", "timing_8c.html", "timing_8c" ],
    [ "timing.h", "timing_8h.html", "timing_8h" ],
    [ "uart.c", "uart_8c.html", "uart_8c" ],
    [ "uart.h", "uart_8h.html", "uart_8h" ]
];